name: Build Workflow
on:
  push:
    branches:
      - package-updates-yarn-semantic-version
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Setup .npmrc
        run: printf "@voltz:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ${{ github.workspace }}/.npmrc
      - name: Install dependencies
        run: make install-ci
      - name: Lint
        run: make lint
      - name: Compile contracts
        run: make compile
      - name: Run tests
        run: make test
      - name: Release
        run: make release
